stages:
  - check
  - mirror

check:
  stage: check
  script:
    - cargo cmd checks
    - cargo nextest run --workspace --lib --no-default-features --cargo-profile dev --target x86_64-unknown-linux-gnu
    - cargo tarpaulin --skip-clean --workspace --lib --no-default-features --target-dir=target/coverage --out Xml
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

mirror:
  stage: mirror
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git checkout -B main
    - git push --mirror git@github.com:arcnode-io/ems-industrial-fixtures.git
  only:
    - main
