stages:
  - check
  - publish
  - mirror

check:
  stage: check
  script:
    - cargo cmd checks
    - cargo nextest run --workspace --lib --no-default-features --cargo-profile dev --target x86_64-unknown-linux-gnu
    - cargo tarpaulin --skip-clean --workspace --lib --no-default-features --target-dir=target/coverage --out Xml
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

publish-mock-modbus-server:
  stage: publish
  script:
    - docker login -u admin -p $HARBOR_PASSWORD 173.211.12.43:8083
    - docker build -f mock-modbus-server/Dockerfile -t 173.211.12.43:8083/library/mock-modbus-server .
    - docker push 173.211.12.43:8083/library/mock-modbus-server
  only:
    - main

publish-mock-snmp-agent:
  stage: publish
  script:
    - docker login -u admin -p $HARBOR_PASSWORD 173.211.12.43:8083
    - docker build -f mock-snmp-agent/Dockerfile -t 173.211.12.43:8083/library/mock-snmp-agent .
    - docker push 173.211.12.43:8083/library/mock-snmp-agent
  only:
    - main

publish-mock-redfish-service:
  stage: publish
  script:
    - docker login -u admin -p $HARBOR_PASSWORD 173.211.12.43:8083
    - docker build -f mock-redfish-service/Dockerfile -t 173.211.12.43:8083/library/mock-redfish-service .
    - docker push 173.211.12.43:8083/library/mock-redfish-service
  only:
    - main

publish-mock-dnp3-outstation:
  stage: publish
  script:
    - docker login -u admin -p $HARBOR_PASSWORD 173.211.12.43:8083
    - docker build -f mock-dnp3-outstation/Dockerfile -t 173.211.12.43:8083/library/mock-dnp3-outstation .
    - docker push 173.211.12.43:8083/library/mock-dnp3-outstation
  only:
    - main

mirror:
  stage: mirror
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git checkout -B main
    - git push --mirror git@github.com:arcnode-io/ems-industrial-fixtures.git
  only:
    - main
